let promise1 = Promise.resolve(34);

let promise2 = 10;

let promise3 = new Promise((resolve, reject)=> {
  setTimeout(resolve, 10, 'foo');
});

Promise.myAll = function(values) {
  return new Promise((resolve, reject)=> {
    let completed = 0;
    let results = [];
    
    values.forEach((value, index)=> {
      Promise.resolve(value).then((result)=> {
        completed++;
        results[index] = result;
        if (completed == values.length) {
          resolve(results);
        }
      }).catch(err=> {
        console.log(err);
      })
    })
    
  })
}


Promise.myAll([promise1, promise2, promise3]).then((data) => {
  console.log(data)
}).catch(data=> {
  console.log("error in catch");
  console.log(data);
})